/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  ARMY
 * Created: Mar 7, 2017
 */
INSERT INTO ACCOUNTS (
    account_email,
    account_username,
    account_password,
    account_name,
    account_lastname,
    account_age,
    account_sex,
    account_sexual_taste,
    account_latitude,
    account_longtitude,
    account_location,
    account_img_profile_path,
    account_descriptions)
VALUES ("acc1@testmail.com",
    "account1",
    "123456",
    "Sara",
    "Hara",
    12,
    "Female",
    "Normal",
    13.719440,
    100.783681,
    "Bangkok",
    "path_test",
    "Hello World!");

INSERT INTO ACCOUNTS (
    account_email,
    account_username,
    account_password,
    account_name,
    account_lastname,
    account_age,
    account_sex,
    account_sexual_taste,
    account_latitude,
    account_longtitude,
    account_location,
    account_img_profile_path,
    account_descriptions)
VALUES ("acc2@testmail.com",
    "account2",
    "123456",
    "Kalvin",
    "regnard",
    20,
    "Male",
    "Normal",
    13.723086,
    100.747511,
    "Bangkok",
    "path_test",
    "Pls chat to me.");

INSERT INTO ACCOUNTS (
    account_email,
    account_username,
    account_password,
    account_name,
    account_lastname,
    account_age,
    account_sex,
    account_sexual_taste,
    account_latitude,
    account_longtitude,
    account_location,
    account_img_profile_path,
    account_descriptions)
VALUES ("acc3@testmail.com",
    "account3",
    "123456",
    "Kalli",
    "Yusong",
    21,
    "Male",
    "Bottom",
    13.770049,
    100.637720,
    "Bangkapi",
    "path_test",
    "I'm gay nice to see you :D");

INSERT INTO ACCOUNTS (
    account_email,
    account_username,
    account_password,
    account_name,
    account_lastname,
    account_age,
    account_sex,
    account_sexual_taste,
    account_latitude,
    account_longtitude,
    account_location,
    account_img_profile_path,
    account_descriptions)
VALUES ("acc4@testmail.com",
    "account4",
    "123456",
    "Cara",
    "Atuditu",
    18,
    "Female",
    "Top",
    12.665664,
    101.044129,
    "Rayong",
    "path_test",
    "Love sea & sky");

INSERT INTO ACCOUNTS (
    account_email,
    account_username,
    account_password,
    account_name,
    account_lastname,
    account_age,
    account_sex,
    account_sexual_taste,
    account_latitude,
    account_longtitude,
    account_location,
    account_img_profile_path,
    account_descriptions)
VALUES ("acc5@testmail.com",
    "account5",
    "123456",
    "Kornasak",
    "Watunnakul",
    30,
    "Male",
    "Top",
    8.018046,
    98.832868,
    "Krabi",
    "path_test",
    "South Asia XD");

INSERT INTO ACCOUNTS (
    account_email,
    account_username,
    account_password,
    account_name,
    account_lastname,
    account_age,
    account_sex,
    account_sexual_taste,
    account_latitude,
    account_longtitude,
    account_location,
    account_img_profile_path,
    account_descriptions)
VALUES ("acc6@testmail.com",
    "account6",
    "123456",
    "Dyran",
    "Yermata",
    50,
    "Female",
    "Bottom",
    19.901495,
    99.830037,
    "Chiang Rai",
    "path_test",
    "Looking for relationship");

INSERT INTO ACCOUNTS (
    account_email,
    account_username,
    account_password,
    account_name,
    account_lastname,
    account_age,
    account_sex,
    account_sexual_taste,
    account_latitude,
    account_longtitude,
    account_location,
    account_img_profile_path,
    account_descriptions)
VALUES ("acc7@testmail.com",
    "account7",
    "123456",
    "Harry",
    "Pottrait",
    25,
    "Male",
    "Top",
    14.006763,
    101.706298,
    "Prachin Buri",
    "path_test",
    "Nice guy :)");

INSERT INTO ACCOUNTS (
    account_email,
    account_username,
    account_password,
    account_name,
    account_lastname,
    account_age,
    account_sex,
    account_sexual_taste,
    account_latitude,
    account_longtitude,
    account_location,
    account_img_profile_path,
    account_descriptions)
VALUES ("acc8@testmail.com",
    "account8",
    "123456",
    "Siri",
    "Sophomore",
    22,
    "Female",
    "Bottom",
    13.377876,
    99.992981,
    "Samut Songkhram",
    "path_test",
    "Match me!!!");

INSERT INTO ACCOUNTS (
    account_email,
    account_username,
    account_password,
    account_name,
    account_lastname,
    account_age,
    account_sex,
    account_sexual_taste,
    account_latitude,
    account_longtitude,
    account_location,
    account_img_profile_path,
    account_descriptions)
VALUES ("acc9@testmail.com",
    "account9",
    "123456",
    "Harit",
    "Burapa",
    19,
    "Male",
    "Normal",
    13.751848,
    100.500593,
    "Bangkok",
    "path_test",
    "Hello World!");

INSERT INTO ACCOUNTS (
    account_email,
    account_username,
    account_password,
    account_name,
    account_lastname,
    account_age,
    account_sex,
    account_sexual_taste,
    account_latitude,
    account_longtitude,
    account_location,
    account_img_profile_path,
    account_descriptions)
VALUES ("acc10@testmail.com",
    "account10",
    "123456",
    "Araya",
    "Sweethome",
    26,
    "Female",
    "Normal",
    16.433940,
    103.505526,
    "Kalasin",
    "path_test",
    "Hi my friends");

